// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBmegos15wf5XSjC2IM5Ayj5wREJLTWajo',
    appId: '1:858409667624:web:67669b76e6b2f5126eb91d',
    messagingSenderId: '858409667624',
    projectId: 'project-nist-17ac9',
    authDomain: 'project-nist-17ac9.firebaseapp.com',
    storageBucket: 'project-nist-17ac9.appspot.com',
    measurementId: 'G-0B2LB3L113',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDyrzwcpysHcI8kRTj7ZDRN3qLRQHKPWkE',
    appId: '1:858409667624:android:eb24dec0f41205016eb91d',
    messagingSenderId: '858409667624',
    projectId: 'project-nist-17ac9',
    storageBucket: 'project-nist-17ac9.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDlcb5RQLa8X6jLCEIDVYwOpSN2A1P9H9k',
    appId: '1:858409667624:ios:a66c386b6c24498d6eb91d',
    messagingSenderId: '858409667624',
    projectId: 'project-nist-17ac9',
    storageBucket: 'project-nist-17ac9.appspot.com',
    iosBundleId: 'com.example.projectNist',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDlcb5RQLa8X6jLCEIDVYwOpSN2A1P9H9k',
    appId: '1:858409667624:ios:a66c386b6c24498d6eb91d',
    messagingSenderId: '858409667624',
    projectId: 'project-nist-17ac9',
    storageBucket: 'project-nist-17ac9.appspot.com',
    iosBundleId: 'com.example.projectNist',
  );
}
